### ISSUE TITLE
Risk factors in all categories need rewrite

### ISSUE THREAD

**Issue by planetlevel** [OWASP/API-Security#105]
The approach to risk scoring that's being used is described here: https://owasp.org/www-project-top-ten/2017/Note_About_Risks

In this draft, the text in the Exploitability, Prevalence, Detectability, and Impact table at the top of each category doesn't match the methodology very well.

Currently, the text in the likelihood boxes is a bit mixed up.  Some list prevalence factors in the exploitability box.  Others don't describe the prevalence factors at all.  Most of the detectability descriptions focus on detection of *exploits* (with logging etc...) rather than factors related to detecting *vulnerabilities*.   The technical impact descriptions are mostly okay - maybe revisit with CIAA in mind.

* Exploitability is supposed to describe how easy is it for expected threat agents to actually exploit this vulnerability? Theoretical (1), difficult (3), easy (5), exploits published (9)

* Prevalence is supposed to describe how widespread this class of vulnerability is. Data would be very helpful here.

* Detectability is supposed to describe the awareness of this vulnerability and how difficult it is to discover. Practically impossible (1), difficult (3), easy (7), automated tools available (9)

* Technical Impact should estimate the magnitude of the damage to confidentiality, integrity, availability, and accountability if this vulnerability were to be exploited.

Note that we should probably continue the practice of having an empty box at the beginning for "threat agent" since we can't know about a user's specific threat profile.  And an empty box for business impact out as it is impossible to gauge without context.  So there should be six total boxes.

**Comment by ErezYalon** [comment]
Thanks, @planetlevel. This feedback is very helpful.
I agree that this entire section requires a rewrite.

**Comment by planetlevel** [comment]
No no no....   Removing these tables is not the right solution.  You could at least discuss some of the factors that contribute to understanding the likelihood and impact of these risk areas.   This is kind of the whole point of a Top Ten.

**Comment by gavjl** [comment]
Please don’t do remove these tables.

The data points and the high-level descriptions for attack vectors / weaknesses / impacts really help to make each entry of the top 10 more accessible. They help to make people want to read the detail instead of just facing a wall of text, they help to give the information another dimension and appeal to a wider variety of specialties.

The data points such as exploitability and prevalence make it easier to envisage (and potentially assess) risk and drive businesses to look closely at these vulnerabilities in their products.

I raised an issue a while ago saying the scores meant ordering was wrong, I hope this didn't help drive the decision to remove them. I’d honestly rather the order was wrong than have these tables removed.

**Comment by PauloASilva** [comment]
Thanks for the feedback!
We should bring them back shortly.
