### ISSUE TITLE
Translation to AR

### ISSUE THREAD

**Issue by Malajab** [OWASP/API-Security#41]
Hey!

I really appreciate your efforts and think this projects should be translated into as many languages as possible.
I'd like to provide a translation into Arabic .

Thanks 
Malek aldossary

**Comment by PauloASilva** [comment]
Hi @Malajab,
Thanks for contributing.

Since you're the first person requesting the Arabic translation, this issue will be assigned to you.
Now it's up to you to lead/manage the effort. It would be great to get the translation reviewed by others.

Cheers,
Paulo A. Silva

**Comment by Malajab** [comment]
Dear @PauloASilva 
Thanks for your reply and support.
Eng. @KINGSABRI he will request PR today as we agreed.
Thanks.

**Comment by PauloASilva** [comment]
Hi guys,
Congratulations!

The Arabic translation was released, check out [v1.4.0](https://github.com/OWASP/API-Security/releases/tag/v1.4.0).

Would you like to provide translators' profile URL (e.g. Linkedin, Twitter, ...) so that [translations list](https://owasp.org/www-project-api-security/#div-translations) can be updated accordingly?

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
The website was updated accordingly.

Thank you for giving back,
Paulo A. Silva
