### ISSUE TITLE
More relatable Security Misconfiguration scenario

### ISSUE THREAD

**Issue by flascelles** [OWASP/API-Security#5]
We came across a real-world example of a security misconfiguration at a customer’s API which is easy to understand and is relatable:

“A team is tasked with implementing a REST API with associated access control rules. At implementation time, the team implements a thin REST API layer on top of a legacy XML service (SOAP to REST). An attacker aware of this legacy service sends requests with content-type of this legacy service to new publicly available REST endpoint. At the API entry point, the service detects the legacy format in the request and skips the new REST layer along with associated access control rules. API calls are passed to legacy XML service without any authentication or access control rules applied.”

**Comment by inonshk** [comment]
Thank you for sharing the example!
Content-type mismatch issues are common in APIs and an I've personally had a few chances to exploit them.
Me, Erez, Paulo and David discussed it today and we decided that even though the issue is common in APIs, it's more related to "hybrid" environments that contain legacy APIs together with modern APIs.
Our vision for the project is to address to modern issues in API security, that are very prevalent today and will be probably prevalent in a couple of years.
On top of that, it's not very clear to provide "how to fix" recommendations for the example you shared with us. It doesn't sound like a good idea to share the same authentication / authorization configuration between two different APIs (especially when one of them is legacy). It might be a deeper architecture issue, related to API gate way configuration, the implementation of the auth/authz system, etc..
