### ISSUE TITLE
Bahasa(Indonesian) Translation

### ISSUE THREAD

**Issue by faizzaidi** [OWASP/API-Security#66]
We want to translate API-Security into Bahasa, any contributors are welcome!

**Comment by PauloASilva** [comment]
Hi @faizzaidi,
I am not sure whether you're talking about the `2019` or `2023RC` edition.
Note that the latter is just a release candidate (RC) which is expected to change until its final version.

Although it was published in 2019, the first API Security Top 10 edition is sill valuable and deserves to be translated in as many languages as possible. If you're willing to translate it, let me know so that I can assign this issue to you.

Best,
Paulo A. Silva

**Comment by faizzaidi** [comment]
Hi @PauloASilva, 

We will do it for both the 2019 and 2023RC editions.

**Comment by PauloASilva** [comment]
Hi @faizzaidi,
Not sure what progress you've made here so far, nevertheless I would like to get your attention to the fact that this repository has changed so that a static website can be built from the source markdown.

You may need to update the fork you're working on.

Best,
Paulo A. Silva

**Comment by faizzaidi** [comment]
Hi @PauloASilva ,

The content is ready for both the versions (2019 and 2023) updated standard. Please help me to understand which branch I should use to commit these changes.

Thanks,
Faiz

**Comment by PauloASilva** [comment]
Hi @faizzaidi,
Please, open the Pull Request to the `develop`  branch.

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
@faizzaidi please diregard my previous comment: I've changed your PR already!

I should review it shortly but some help will be required to perform the proof reading.
Fill free to announce your work in social media: you may found someone willing to proof reading it.

Thanks for giving back to the community.

Paulo A. Silva

**Comment by faizzaidi** [comment]
Sure @PauloASilva, 

Please help us understand what exactly is proof reading. Do you need a short audio/video recording of reading the Bahasa version or something else? I also had words with @dalfian; he can also help us with the second level of review. 

It's always a pleasure working with OWASP, and I have learned a lot from it.

**Comment by PauloASilva** [comment]
Hi @faizzaidi,
Proofreading is the final stage of checking a text before it is published or shared. With this process you should be able to, for example, find & fix typos or make sentences more clear where required.

Since I don't speak the language I won't be of much help here. My review will focus on "coding standards" and the build process.

I've reached out to the community requesting for help on my social media and OWASP slack.
Feel free to do the same on your social media channels.

Cheers,
Paulo A. Silva

**Comment by tedher** [comment]
Hi @PauloASilva and @faizzaidi, 

I can help to proofread the 2023 translation.

**Comment by tedher** [comment]
@faizzaidi I noticed that you use "ba" for Indonesian language code. 

According to ISO-639-1 (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), it should be "id".

**Comment by faizzaidi** [comment]
Dear @tedher,
We have updated the directory as per your suggestion. Kindly find the request https://github.com/OWASP/API-Security/pull/125/commits/51dc48c40fd9e5746c795d2cd79c549847326ef3.

Thanks,
Faiz
