### ISSUE TITLE
Incorrect order is applied?

### ISSUE THREAD

**Issue by gavjl** [OWASP/API-Security#82]
Assuming scores are based on the way previous top 10's have worked:

((Exploitability + Prevalence + Detectability)/3) * Technical impact

The entries aren't in the correct order

**Comment by planetlevel** [comment]
Would love to see a table listing out the entries (along with the other important API risks I've mentioned) and the details of this calculation.   I think it will make clear that the entries aren't the right ones.

**Comment by gavjl** [comment]
For reference, the current scores look like:

		exploitability	prevalence	detectability	tech impact		Score
API1:2023	3			3		2			3			8
API2:2023	3			2		2			3			7
API3:2023	3			2		2			2			4.666666667
API4:2023	2			3		3			2			5.333333333
API5:2023	3			2		1			2			4
API6:2023	2			2		1			2			3.333333333
API7:2023	3			3		3			2			6
API8:2023	3			3		1			1			2.333333333
API9:2023	3			3		2			2			5.333333333
API10:2023	2			2		1			3			5

In previous top 10 lists the scoring hasn't been very obvious, I've heard lots of people suggest they aren't ordered lists, completely unaware of the scoring used.

**Comment by planetlevel** [comment]
Whether they're aware of it or not, a massive amount of data science, led by Dr. Brian Glas, was performed for the main OWASP T10. I know for a fact the outcome represents months of work for a team of people.  Read the methodology section in the document.  https://owasp.org/Top10/A00_2021_Introduction/

My request was to do this exercise for the list of categories I suggested, in addition to these, so that we could see how you've rated all the risks side-by-side.   It's very obvious to me that the risks here -- like mass assignment (infrequent, often harmless) are way less serious than the use of insecure libraries in APIs (incredibly prevalent, often highly dangerous).

I guess it doesn't matter since it's obvious.   The remaining question is whether the API T10 will be changed to cover the top risks to APIs.    Or will it remain a document that only includes risks not covered in the Main T10 and only for APIs written in the past few years.

**Comment by gavjl** [comment]
I agree entirely with your comments on the subject on some of the other issues. 

An awareness document for the top vulnerabilities in APIs that omits the most serious vulnerabilities in APIs is ...challenging
