### ISSUE TITLE
OWASP 2021 categories don’t apply to the new list

### ISSUE THREAD

**Issue by PauloASilva** [OWASP/API-Security#83]
> At a minimum, I would love to know why the following categories from the main OWASP T10 don't apply to APIs:
>
>     * Injection
>     * Cryptographic Failures
>     * Insecure Design
>     * Vulnerable and Outdated Components
>     * Software and Data Integrity Failures
(Source: issue #77 by @planetlevel)

**Comment by inonshk** [comment]
While the flagship OWASP Top 10 is relevant for every application, and is very generic, the OWASP **API** Top 10 tries to address issues that are more specific to APIs. Addressing these issues means we take into account issues that are more common, trending, or have different ways to handle/remediate in a modern API-centric application. Our goal is not to create the same list as the OWASP Top 10, nor to interpret it and explain how its categories are reflected in APIs (like some other Top10 projects).


The OWASP **API** Top 10 - 2023 version is different from the 2019 version. We aspire to follow the security trends that are relevant to APIs and have been developed in recent years.
If you try to hack or protect an API that was developed 5 years ago, it would make more sense to refer to the 2019 list.

Let me explain why we think it’s the right decision to remove the following categories:

**Injections**

Injection used to be the most severe threat when it comes to web applications for many years.
Based on past data - there are two types of injections that have made this category so severe and prevalent, which are:
1. SQL Injection 
2. Command/Shell Injection.

These types of injection are less common in API-Centric applications that have been developed in recent years, because of the following reasons:

1. More developers choose to use ORM environments that protect against most types of SQL Injections by default. Even though it is possible to write vulnerable code while using an ORM - it is much less common.
2. With the rise of Cloud-Native, it is less common to see developers using shell commands inside the application code. Doing so makes the application less scalable in the Docker/K8S environments.
3. It is no longer common to see developers using shell commands in order to leverage CLI tools (for example: for graphics purposes). Modern frameworks and the abundance of third party libraries/APIs, make this trend less common in modern applications, since it is easier to find a library you can call to within the code itself, instead of a CLI tool.
4. Hundreds if not thousands of solutions have been built around SQL/Shell Injection protection.

The main goal of the **API** Top 10 document is to bring awareness to API specific issues. After almost 20 years in the Top 10 list, and every secure coding course containing injection lessons, we believe that there is a place to bring awareness to other areas.
Having said that, injection is indeed still an unsolved problem and we are happy to still see it in the general Top 10 and don’t believe that it should be echoed in every Top 10 project.

**Cryptographic Failures**
We don’t see this issue as an API specific issue, but more as a general secure coding problem.
We did include some of the sub-issues under “Security Misconfiguration”


**Insecure Design**
We acknowledge the big risk of insecure design, and believe it should be a part of the general Top 10. However, if we review the current issues that are under the huge umbrella of “Insecure Design” in OWASP Top 10 2021, we believe that many of them are not API Specific.
There is one main category of problems that is more specific to APIs, which is “Lack of automated threats”. Two of the three examples in the 2021 list talk about automated threats (“bots”) mitigation. We believe that this category deserves its own place on the list, and this is why we separated it from the generic “Insecure Design”.
Vulnerable and Outdated Components
Having protocols and policies to update the organization’s systems, frameworks, libraries, etc is an important part of software composition security and the security posture of the organization - but we don’t view it as an API specific related issue.

**Software and Data Integrity Failures**
We don’t view this issue as API Specific.

**Comment by planetlevel** [comment]
Thx for responding.  I appreciate, maybe better than anyone, how difficult creating a Top Ten can be.  I want to thank you for creating this and pushing forward an important effort.

I'm very concerned that this API T10 will be misleading because it doesn't include the top risks to APIs. 
Instead, your philosophy seems to be only including items that ONLY apply to modern APIs.  Unfortunately, you haven't explained that so people's assumptions will be wrong.  And even if you did explain it, I don't think you've achieved your goal.

> While the flagship OWASP Top 10 is relevant for every application, and is very generic, the OWASP API Top 10 tries to address issues that are more specific to APIs. Addressing these issues means we take into account issues that are more common, trending, or have different ways to handle/remediate in a modern API-centric application.

Are you suggesting that there's a different set of criteria for selecting than what represents the biggest risks to organizations building APIs?  If so, I'd love to understand the exact criteria for what's included and what's not.

> The OWASP API Top 10 - 2023 version is different from the 2019 version. We aspire to follow the security trends that are relevant to APIs and have been developed in recent years.

So is this API Top 10 intended only for recently built APIs?  If so, we need a gigantic disclaimer on the website and document to prevent misunderstandings.

> Injection used to be the most severe threat when it comes to web applications for many years. These types of injection are less common in API-Centric applications that have been developed in recent years, because of the following reasons:

I have a ton of data from hundreds of thousands of APIs that says this isn't correct.  Do you have data that you can share that supports these assertions? Also, there are dozens of types of injection not just two.

> Hundreds if not thousands of solutions have been built around SQL/Shell Injection protection.
The main goal of the API Top 10 document is to bring awareness to API specific issues. After almost 20 years in the Top 10 list, and every secure coding course containing injection lessons, we believe that there is a place to bring awareness to other areas.  Having said that, injection is indeed still an unsolved problem and we are happy to still see it in the general Top 10 and don’t believe that it should be echoed in every Top 10 project.

This is the crux of the problem.  I don't believe that people are thinking of the API Top Ten as an addendum or extension of the main Top Ten.  They think of it as the top ten API security risks.  I don't care if there's overlap, you need to tell API developers the top risks.

> Cryptographic Failures. We don’t see this issue as an API specific issue, but more as a general secure coding problem.

First of all, cryptographic problems are critical for APIs.  But more importantly, literally NONE of the API Top Ten items are "API specific."  Every single one of them is relevant to traditional web apps, older APIs, and other types of apps.... including modern APIs and serverless functions.  You've provided no data analysis, and I can't see any principled distinction for including some items in both docs and some not.  You include SSRF (which is in the main OWASP T10) but not crypto.  You include authentication, misconfiguration, and others that are in the main T10, but not injection, crypto, design, integrity.

And what's worse is that there is no warning or explanation about why these choices were made. 

> Insecure Design
> Vulnerable and Outdated Components
> Software and Data Integrity Failures

I don't find your explanation for not including these areas compelling.  Essentially your argument is just that "we don't think they apply."   I'm asking you to justify this claim before folks rely on this document and make some really bad risk decisions.  Provide some data that shows that the use of insecure libraries is less important to API security than unsafe consumption of APIs or lack of protection from automated threats.   Explain to me why we need 6 different flavors of authorization issues instead of some areas that IMO (and backed by a lot of data) are clearly relevant to APIs.
