### ISSUE TITLE
JSON Parameter Pollution

### ISSUE THREAD

**Issue by pentagramz** [OWASP/API-Security#9]
JSON Parameter Pollution is a common issue I find in API and not that checked upon often, which I feel can be added in the list

**Comment by inonshk** [comment]
We were thinking about the option to create a special category for the following items:
- HTTP Parameter Pollution
- JSON Parameter Pollution
- Content-type Manipulation (sending an XML instead of a JSON to bypass mechanisms)

I agree these are common in APIs.
Anyway, these techniques are used only to bypass security mechanisms, rather than exploiting a specific security issue.
Layered security is a great concept, but let's say you managed to bypass a WAF or white-list filtering by using JSON Parameter Pollution,what led to an exploitation of a vulnerability like XSS / SQLi.

This is cool. But there's a bigger problem than the parameter pollution - which is the fact the application code is vulnerable to XSS / SQLi.

**Comment by pentagramz** [comment]
JSON Parameter Pollution i did not meant bypassing waf or white list filtering. I have valid scenarios where the business logic of the app is bypassed such as accepting values for transaction amounts , selecting options not intended by user etc.

We are not bypassing anything or going to a secondary underlying condition but the behaviour of the app can be changed which the user did not intended to in the first place.

**Comment by pentagramz** [comment]
Let me know your views , and not necessary we are adding in Top 10 but just in case we have a guide or cheatsheet in pipeline these are scenarios we can add for developers .

**Comment by inonshk** [comment]
@pentagramz 
Thank you for your response and your feedback! we're really happy to receive comments from professionals in the field.

I'm really curious to see these scenarios you mentioned, please share them if you can.
The JSON Parameter Pollution attack vector is pretty similar to [HTTP Parameter Pollution](https://www.owasp.org/index.php/Testing_for_HTTP_Parameter_pollution_(OTG-INPVAL-004)),
and I think it should be in the [OWASP Testing Guide](https://www.owasp.org/index.php/OWASP_Testing_Project).

Mine views about this attack vector are: it's pretty common, but not in every environment.
It usually happens when you have a security mechanism (input-validation, signatures based, etc) that is implemented in a different component than the vulnerable application code itself.
This component usually runs in a different framework/programming language/JSON parsing library, that processes the JSON in a different way.  

After we finish with top 10 list, we'll publish other documents related to API security. One of them might be a cheatsheet for pentesters. In this case, I'll definitely add information about this attack vector.
Thank you!
